export interface regismdl {
    ccregId: number,
    ccregName: String,
    ccregNickName: String,
    ccregNationId: String,
    ccregNationImgFileName: String,
    ccregNationImgFilePath: String,
    ccregNibId: String,
    ccregNibImgFileName: String,
    ccregNibImgFilePath: String,
    ccregAddress: String,
    ccregRt: String,
    ccregRw: String,
    ccregProvId: String,
    ccregCityId: String,
    ccregKecId: String,
    ccregKelId: String,
    ccregArea: String,
    ccregZip: String,
    ccregMobilePhone: String,
    ccregPhone: String,
    ccregEmail: String,
    ccregLongLat: String,
    ccregSentCmbaId: String,
    ccregSentCmbaName: String,
    ccregSentCmbaAccount: String,
    ccregRevcCmbaId: String,
    ccregRecvCmbaName: String,
    ccregRevcCmbaAccount: String,
    ccregMinApproval: number,
    ccregPic1Name: String,
    ccregPic1Phone: String,
    ccregPic1Email: String,
    ccregPic1password: String,
    ccregPic2Name: String,
    ccregPic2Phone: String,
    ccregPic2Email: String,
    ccregPic2password: String,
    ccregPic3Name: String,
    ccregPic3Phone: String,
    ccregPic3Email: String,
    ccregPic3password: String,
    ccreg_type:string
}

